json.id song.id
json.artistId song.user_id
json.title song.title
json.imageUrl asset_path(song.image.url)
json.audioUrl song.audio.url
json.createdAt song.created_at
json.numLikes song.likes.length
json.numReposts song.reposts.length
json.plays song.plays
